"""Weekly CEO memo as Markdown (``GET /ceo/weekly.md``), watermarked (D11)."""
from __future__ import annotations

from .. import definitions as D
from . import ceo

WATERMARK = "Synthetic data — illustrative"


def _fmt(v, unit: str) -> str:
    if v is None:
        return "—"
    if unit == "contracts":
        return f"{v:,.0f}"
    if unit == "usd":
        return f"${v:,.0f}"
    if unit == "usd_mwh":
        return f"${v:,.2f}/MWh"
    if unit in ("rate", "share"):
        return f"{v:.1%}"
    if unit == "ratio":
        return f"{v:.2f}×"
    if unit == "days":
        return f"{v:.1f} d"
    if unit == "accounts":
        return f"{v:,.1f}" if v != int(v) else f"{int(v):,}"
    return f"{v}"


_STATUS = {"on_track": "On track", "watch": "Watch", "off_track": "Off track"}


def weekly_md(state, week_end=None) -> str:
    w = ceo.weekly(state, week_end)
    L = [
        f"# ElectronX — CEO Weekly, week ending {w['week_end']}",
        "",
        f"> **{WATERMARK}.** Generated by Ignition from a synthetic dataset (as of {w['as_of']}). "
        "Not ElectronX data; every number below is illustrative.",
        "",
        "## This week in three sentences",
        "",
    ]
    L += [f"{i}. {h}" for i, h in enumerate(w["headline"], 1)]
    L += ["", "## Three decisions for Monday", ""]
    L += [f"{i}. {d}" for i, d in enumerate(w["decisions"], 1)]
    L += ["", "## KPIs", "", "| KPI | Value | Prior | Target | Status |", "|---|---:|---:|---:|---|"]
    for k in w["kpis"]:
        tgt = _fmt(k["target"], k["unit"]) if k["target"] is not None else "—"
        if k["target"] is not None:
            tgt = ("≥ " if k["target_direction"] == "min" else "≤ ") + tgt
        L.append(f"| {k['label']} | {_fmt(k['value'], k['unit'])} | {_fmt(k['prior'], k['unit'])} ({k['prior_label']}) | {tgt} | {_STATUS[k['status']]} |")
    m = w["mix"]
    L += ["", "## Market balance", "",
          "| Side | Active accounts | ADV (contracts/day) |", "|---|---:|---:|"]
    for side in D.SIDES:
        L.append(f"| {side.replace('_', ' ')} | {m['by_side_accounts'][side]} | {m['by_side_adv'][side]:,.0f} |")
    L += ["", f"Top-5 share of ADV **{(m['top5_adv_share'] or 0):.1%}** (ceiling 45%) · HHI {(m['hhi'] or 0):.3f} · "
          f"hedger share of Active **{(m['hedger_share_active'] or 0):.1%}** (floor 50%). Liquidity-partner volume is reported as its own line.", ""]
    L += ["## Spread quality (main hubs, last 5 trading days)", "",
          "| ISO | Hub | Tenor | Spread $/MWh | Target | Two-sided uptime | Target | Status |", "|---|---|---|---:|---:|---:|---:|---|"]
    for s in w["spreads"]:
        L.append(f"| {s['iso']} | {s['hub']} | {s['tenor']} | ${s['spread_usd_mwh']:.2f} | ≤ ${s['target_spread']:.2f} | "
                 f"{s['uptime_pct']:.1f}% | ≥ {s['target_uptime']:.0f}% | {_STATUS[s['status']]} |")
    L += ["", "## 30-day cohort activation (4-week funding cohorts)", "",
          "| Cohort start | n | Activated ≤30 d |", "|---|---:|---:|"]
    for c in w["activation_cohorts"]:
        flag = " (n < 20, not decision-grade)" if c["greyed"] else ""
        L.append(f"| {c['cohort_week']} | {c['n']} | {c['activated_30d_rate']:.0%}{flag} |")
    L += ["", f"## Stalled funded accounts ({w['stalled_total']} funded >21 d with no qualifying trade; top {len(w['stalled'])})", "",
          "| Account | Segment | Days since funding | E[ADV] | Next action (owner, SLA) |", "|---|---|---:|---:|---|"]
    for r in w["stalled"]:
        na = r["next_action"] or {}
        L.append(f"| {r['name']} | {r['segment']} | {r['days_stalled']} | {r['exp_adv']:,.0f} | "
                 f"{na.get('action', '—')} ({na.get('owner', '—')}, {na.get('sla') or '—'}) |")
    L += ["", "## Definitions", "",
          "- **Active** = ≥4 distinct trading days in the trailing 30 calendar days. **Active rate** = Active ÷ funded accounts older than 20 days.",
          "- **ADV** = Σ contracts over the trailing 20 trading days ÷ 20; liquidity-partner volume shown separately.",
          "- **Qualifying trade** = fill of ≥10 contracts, non-self-match. Cohorts with n < 20 are not decision-grade.",
          "", "---", f"*{WATERMARK}. Ignition — ElectronX Activation & Revenue OS.*", ""]
    return "\n".join(L)
